// https://github.com/oculus-samples/Unity-DepthAPI/issues/16
#include "DepthKit.hlsl"

#pragma kernel CSMain

#if defined(SHADER_API_D3D11)
#define FLIP_UVS 1
#endif

StructuredBuffer<float2> Requests;
RWStructuredBuffer<float3> Results;

[numthreads(64, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID) 
{
	const uint i = id.x;
	
	float3 ndc = float3(Requests[i].x, Requests[i].y, 1);
	ndc.z = agDepthSample(ndc.xy, 0);
	
	Results[i] = agDepthNDCtoWorld(ndc, 0);
}